version: '3'

services:
  chatservice:
    build: .
    container_name: fclx_chatservice_grpc
    volumes:
      - .:/go/src
    ports:
      - "8081:8080"
      - "50052:50051"
    command: go run cmd/chatservice/main.go &
  # mysql:
  #   image: mysql:8
  #   container_name: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: chat_test
  #     MYSQL_PASSWORD: root
  #   ports:
  #     - 3306:3306  
  #   volumes:
  #     - .docker/mysql:/var/lib/mysql

  #  docker service logs chatservice -f --filter 'name=fclx_chatservice_grpc'
