version: "3"

services:
  app:
    container_name: fclx_next_back
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      # - "host.docker.internal:172.17.0.1"  
      - "host.docker.internal:host-gateway"
      - "kubernets.docker.internal:host-gateway"
      # - "host.docker.internal:172.17.0.1"
      # marco.cianci
    command: npm run dev &
    # networks:
    #   - fcexperience
    # 

  # db:
  #   image: mysql:8.0.30-debian
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=chat
  #   volumes:
  #     - .docker/dbdata:/var/lib/mysql
     # networks:
     #   - fcexperience
  
  keycloak:
    image: quay.io/keycloak/keycloak:21.0
    command: start-dev
    ports:
      - 9000:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    # networks:
    #   - fcexperience

# networks:
#   fcexperience:
#     external: true

# Mac e Linux
# /etc/hosts

# 127.0.0.1 host.docker.internal

# Windows
# C:\Windows\System32\drivers\etc\hosts